spring:
  datasource:
    url: jdbc:mysql://nogin-dev.cdjllt6izrk3.us-east-1.rds.amazonaws.com:3306/sfg_prod
    username: sfg_prod_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true